import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MainLayout from "@/components/layout/MainLayout";
import I18nProvider from "./i18n-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moomkin",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

interface SingleStatePageProps {
  params: Promise<{
    locale: string;
  }>;
  children: React.ReactNode;
}

// hi baby

export default async function RootLayout({
  children,
  params,
}: SingleStatePageProps) {
  const param = await params;
  return (
    <html lang={param.locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider initialLocale={param.locale}>
          <MainLayout>{children}</MainLayout>
        </I18nProvider>
      </body>
    </html>
  );
}
