import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MainLayout from "@/components/layout/MainLayout";
import I18nProvider from "./i18n-provider";
import ProgressBarClient from "@/components/layout/ProgressBarClient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moomkin",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

interface SingleStatePageProps {
  params: Promise<{
    locale: string;
  }>;
  children: React.ReactNode;
}

// hi baby

export default async function RootLayout({
  children,
  params,
}: SingleStatePageProps) {
  const param = await params;
  return (
    <html lang={param.locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-6J223825M8"
          strategy="afterInteractive"
        />
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-6J223825M8');
          `}
        </Script>
        <ProgressBarClient />
        <I18nProvider initialLocale={param.locale}>
          <MainLayout>{children}</MainLayout>
        </I18nProvider>
      </body>
    </html>
  );
}
