name: Deploy Next.js App

on:
  push:
    branches:
      - main   # change this if you use another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Next.js works well with 18+

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/moomkin-web
            git pull origin main
            npm install --production
            npm run build
            pm2 restart moomkin-web || pm2 start npm --name "moomkin-web" -- start
